export const data = [
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: false,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: false,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: false,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: false,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: false,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: false,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: false,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: false,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: true,
  },
  {
    img: "/img-head.svg",
    heading: "Adam Stride",
    price: "$23,750",
    title: "Stocks, Bonds & Real Estate",
    isProfit: false,
  },
];
